node  {

    stage ('SCM')  {
        // git clone
        git 'https://github.com/openmrs/openmrs-core.git'
    }

    stage ('build the packages')  {
        // mvn package
        sh 'mvn package'
    }

    stage ('show test result')  {
        Junit ' target/surefire-reports/*.xml '
    }

    stage ('archival')  {
        // archiving artifact
        archiveArtifacts artifacts: 'target/*.jar'
    }
}
