node  {

    stage ('SCM')  {
        // git clone
        git 'https://github.com/gajulasrikar/Calculator.git'
    }

    stage ('build the packages')  {
        // mvn package
        sh 'mvn package'
    }

    stage ('archival')  {
        // archiving artifact
        archiveArtifacts artifacts: 'target/*.jar'
    }

}